# This workflow will build a Java project with Maven and analyze it with SonarQube, caching dependencies to improve execution time.

name: Java CI with Maven and SonarQube

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml